<ADSWorkspace Revision="18" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_pelib" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Preferences Name="layout.prf" />
        <Preferences Name="schematic.prf" />
        <Library Name="LEARNINGADS_lib" />
        <Log Name="search_history.log" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Preferences Name="LEARNINGADS_lib_lay.prf" />
        <Preferences Name="LEARNINGADS_lib_sch.prf" />
        <ConfigFile Name="dds.cfg" />
        <Data_Display Name="TestBench_MyFilter.dds" />
        <Log Name="netlist.log" />
        <Dataset Name="TestBench_MyFilter.ds" />
        <Data_Files Name="TestBench_MyFilter.ds" />
        <Data_Files Name="TestBench_MyFilter_data\logFile.txt" />
        <Library Name="muRataLibWeb_C_tech" />
        <Library Name="muRataLibWeb_C" />
        <Library Name="muRataLibWeb_L_tech" />
        <Library Name="muRataLibWeb_L" />
        <Data_Files Name="MyFilter_Madara.s2p" />
        <Cell Name="LEARNINGADS_lib:Design1" />
        <Cell Name="LEARNINGADS_lib:Design1_Madara" />
        <Cell Name="LEARNINGADS_lib:Layout1" />
        <Cell Name="LEARNINGADS_lib:TestBench_MyFilter" />
        <Log Name="nettrans.log" />
        <WrkAel Name="spice.ael" />
        <Preferences Name="ads_datacmps_lay.prf" />
        <Library Name="RF_Transistors" />
        <Folder Name="LNA_ATF21170">
            <Folder Name="PART1_DC,STABILITY_AND_BIAS_NW">
                <Cell Name="LEARNINGADS_lib:STEP1_DCIV" />
                <Data_Display Name="STEP1_DCIV.dds" />
                <Cell Name="LEARNINGADS_lib:STEP2_STABILITY" />
                <Data_Display Name="STEP2_STABILITY.dds" />
            </Folder>
        </Folder>
        <Dataset Name="STEP1_DCIV.ds" />
        <Data_Files Name="dc_annotation\%L%E%A%R%N%I%N%G%A%D%S_lib_%S%T%E%P1_%D%C%I%V_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%L%E%A%R%N%I%N%G%A%D%S_lib_%S%T%E%P1_%D%C%I%V_schematic\annotation_map.xml" />
        <Data_Files Name="STEP1_DCIV.ds" />
        <Data_Files Name="STEP1_DCIV_data\logFile.txt" />
        <Dataset Name="STEP2_STABILITY.ds" />
        <Data_Files Name="dc_annotation\%L%E%A%R%N%I%N%G%A%D%S_lib_%S%T%E%P2_%S%T%A%B%I%L%I%T%Y_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\%L%E%A%R%N%I%N%G%A%D%S_lib_%S%T%E%P2_%S%T%A%B%I%L%I%T%Y_schematic\annotation_map.xml" />
        <Data_Files Name="STEP2_STABILITY.ds" />
        <Data_Files Name="STEP2_STABILITY_data\logFile.txt" />
    </Workspace>
</ADSWorkspace>
